// BOTH
#define FETCH_MSG "FETCH"

// SERVER
#define SERVER_RECV_BUF 1024

// CLIENT
#define CLIENT_RECV_BUF 1024

#define ATTACK_RANGE 1

#define DEATH_COOLDOWN 5000
#define KILL_POINT_GAIN 10
#define FLAG_POINT_GAIN 1

#define GAME_UPDATE_RATE 10